// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Document {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  path: string;
  category?: string;
  source_path?: string;
  body?: PortableTextBlock[];
  migration_notes?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    documents: Document;
  }
}